// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/meigma/blobber/v2/internal/estargz"
	"github.com/meigma/blobber/v2/internal/oci"
	"github.com/opencontainers/go-digest"
	ocispec "github.com/opencontainers/image-spec/specs-go/v1"
	"io"
	"sync"
)

// Ensure, that ClientMock does implement oci.Client.
// If this is not the case, regenerate this file with moq.
var _ oci.Client = &ClientMock{}

// ClientMock is a mock implementation of oci.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked oci.Client
//		mockedClient := &ClientMock{
//			BlobReaderFunc: func(ctx context.Context, ref string, desc ocispec.Descriptor) (estargz.BlobSource, error) {
//				panic("mock out the BlobReader method")
//			},
//			FetchBlobFunc: func(ctx context.Context, ref string, desc ocispec.Descriptor) (io.ReadCloser, error) {
//				panic("mock out the FetchBlob method")
//			},
//			FetchBlobRangeFunc: func(ctx context.Context, ref string, desc ocispec.Descriptor, offset int64, length int64) (io.ReadCloser, error) {
//				panic("mock out the FetchBlobRange method")
//			},
//			FetchManifestFunc: func(ctx context.Context, ref string) ([]byte, ocispec.Descriptor, error) {
//				panic("mock out the FetchManifest method")
//			},
//			ListReferrersFunc: func(ctx context.Context, ref string, subjectDigest string, artifactType string) ([]ocispec.Descriptor, error) {
//				panic("mock out the ListReferrers method")
//			},
//			PushBlobFunc: func(ctx context.Context, ref string, desc ocispec.Descriptor, content io.Reader) error {
//				panic("mock out the PushBlob method")
//			},
//			PushManifestFunc: func(ctx context.Context, ref string, desc ocispec.Descriptor, content []byte) error {
//				panic("mock out the PushManifest method")
//			},
//			PushReferrerFunc: func(ctx context.Context, ref string, subject ocispec.Descriptor, artifact ocispec.Descriptor, content []byte) (digest.Digest, error) {
//				panic("mock out the PushReferrer method")
//			},
//			ResolveManifestFunc: func(ctx context.Context, ref string) (ocispec.Descriptor, error) {
//				panic("mock out the ResolveManifest method")
//			},
//			TagFunc: func(ctx context.Context, ref string, desc ocispec.Descriptor, tag string) error {
//				panic("mock out the Tag method")
//			},
//		}
//
//		// use mockedClient in code that requires oci.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// BlobReaderFunc mocks the BlobReader method.
	BlobReaderFunc func(ctx context.Context, ref string, desc ocispec.Descriptor) (estargz.BlobSource, error)

	// FetchBlobFunc mocks the FetchBlob method.
	FetchBlobFunc func(ctx context.Context, ref string, desc ocispec.Descriptor) (io.ReadCloser, error)

	// FetchBlobRangeFunc mocks the FetchBlobRange method.
	FetchBlobRangeFunc func(ctx context.Context, ref string, desc ocispec.Descriptor, offset int64, length int64) (io.ReadCloser, error)

	// FetchManifestFunc mocks the FetchManifest method.
	FetchManifestFunc func(ctx context.Context, ref string) ([]byte, ocispec.Descriptor, error)

	// ListReferrersFunc mocks the ListReferrers method.
	ListReferrersFunc func(ctx context.Context, ref string, subjectDigest string, artifactType string) ([]ocispec.Descriptor, error)

	// PushBlobFunc mocks the PushBlob method.
	PushBlobFunc func(ctx context.Context, ref string, desc ocispec.Descriptor, content io.Reader) error

	// PushManifestFunc mocks the PushManifest method.
	PushManifestFunc func(ctx context.Context, ref string, desc ocispec.Descriptor, content []byte) error

	// PushReferrerFunc mocks the PushReferrer method.
	PushReferrerFunc func(ctx context.Context, ref string, subject ocispec.Descriptor, artifact ocispec.Descriptor, content []byte) (digest.Digest, error)

	// ResolveManifestFunc mocks the ResolveManifest method.
	ResolveManifestFunc func(ctx context.Context, ref string) (ocispec.Descriptor, error)

	// TagFunc mocks the Tag method.
	TagFunc func(ctx context.Context, ref string, desc ocispec.Descriptor, tag string) error

	// calls tracks calls to the methods.
	calls struct {
		// BlobReader holds details about calls to the BlobReader method.
		BlobReader []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Desc is the desc argument value.
			Desc ocispec.Descriptor
		}
		// FetchBlob holds details about calls to the FetchBlob method.
		FetchBlob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Desc is the desc argument value.
			Desc ocispec.Descriptor
		}
		// FetchBlobRange holds details about calls to the FetchBlobRange method.
		FetchBlobRange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Desc is the desc argument value.
			Desc ocispec.Descriptor
			// Offset is the offset argument value.
			Offset int64
			// Length is the length argument value.
			Length int64
		}
		// FetchManifest holds details about calls to the FetchManifest method.
		FetchManifest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
		// ListReferrers holds details about calls to the ListReferrers method.
		ListReferrers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// SubjectDigest is the subjectDigest argument value.
			SubjectDigest string
			// ArtifactType is the artifactType argument value.
			ArtifactType string
		}
		// PushBlob holds details about calls to the PushBlob method.
		PushBlob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Desc is the desc argument value.
			Desc ocispec.Descriptor
			// Content is the content argument value.
			Content io.Reader
		}
		// PushManifest holds details about calls to the PushManifest method.
		PushManifest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Desc is the desc argument value.
			Desc ocispec.Descriptor
			// Content is the content argument value.
			Content []byte
		}
		// PushReferrer holds details about calls to the PushReferrer method.
		PushReferrer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Subject is the subject argument value.
			Subject ocispec.Descriptor
			// Artifact is the artifact argument value.
			Artifact ocispec.Descriptor
			// Content is the content argument value.
			Content []byte
		}
		// ResolveManifest holds details about calls to the ResolveManifest method.
		ResolveManifest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
		// Tag holds details about calls to the Tag method.
		Tag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Desc is the desc argument value.
			Desc ocispec.Descriptor
			// Tag is the tag argument value.
			Tag string
		}
	}
	lockBlobReader      sync.RWMutex
	lockFetchBlob       sync.RWMutex
	lockFetchBlobRange  sync.RWMutex
	lockFetchManifest   sync.RWMutex
	lockListReferrers   sync.RWMutex
	lockPushBlob        sync.RWMutex
	lockPushManifest    sync.RWMutex
	lockPushReferrer    sync.RWMutex
	lockResolveManifest sync.RWMutex
	lockTag             sync.RWMutex
}

// BlobReader calls BlobReaderFunc.
func (mock *ClientMock) BlobReader(ctx context.Context, ref string, desc ocispec.Descriptor) (estargz.BlobSource, error) {
	if mock.BlobReaderFunc == nil {
		panic("ClientMock.BlobReaderFunc: method is nil but Client.BlobReader was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Ref  string
		Desc ocispec.Descriptor
	}{
		Ctx:  ctx,
		Ref:  ref,
		Desc: desc,
	}
	mock.lockBlobReader.Lock()
	mock.calls.BlobReader = append(mock.calls.BlobReader, callInfo)
	mock.lockBlobReader.Unlock()
	return mock.BlobReaderFunc(ctx, ref, desc)
}

// BlobReaderCalls gets all the calls that were made to BlobReader.
// Check the length with:
//
//	len(mockedClient.BlobReaderCalls())
func (mock *ClientMock) BlobReaderCalls() []struct {
	Ctx  context.Context
	Ref  string
	Desc ocispec.Descriptor
} {
	var calls []struct {
		Ctx  context.Context
		Ref  string
		Desc ocispec.Descriptor
	}
	mock.lockBlobReader.RLock()
	calls = mock.calls.BlobReader
	mock.lockBlobReader.RUnlock()
	return calls
}

// FetchBlob calls FetchBlobFunc.
func (mock *ClientMock) FetchBlob(ctx context.Context, ref string, desc ocispec.Descriptor) (io.ReadCloser, error) {
	if mock.FetchBlobFunc == nil {
		panic("ClientMock.FetchBlobFunc: method is nil but Client.FetchBlob was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Ref  string
		Desc ocispec.Descriptor
	}{
		Ctx:  ctx,
		Ref:  ref,
		Desc: desc,
	}
	mock.lockFetchBlob.Lock()
	mock.calls.FetchBlob = append(mock.calls.FetchBlob, callInfo)
	mock.lockFetchBlob.Unlock()
	return mock.FetchBlobFunc(ctx, ref, desc)
}

// FetchBlobCalls gets all the calls that were made to FetchBlob.
// Check the length with:
//
//	len(mockedClient.FetchBlobCalls())
func (mock *ClientMock) FetchBlobCalls() []struct {
	Ctx  context.Context
	Ref  string
	Desc ocispec.Descriptor
} {
	var calls []struct {
		Ctx  context.Context
		Ref  string
		Desc ocispec.Descriptor
	}
	mock.lockFetchBlob.RLock()
	calls = mock.calls.FetchBlob
	mock.lockFetchBlob.RUnlock()
	return calls
}

// FetchBlobRange calls FetchBlobRangeFunc.
func (mock *ClientMock) FetchBlobRange(ctx context.Context, ref string, desc ocispec.Descriptor, offset int64, length int64) (io.ReadCloser, error) {
	if mock.FetchBlobRangeFunc == nil {
		panic("ClientMock.FetchBlobRangeFunc: method is nil but Client.FetchBlobRange was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Ref    string
		Desc   ocispec.Descriptor
		Offset int64
		Length int64
	}{
		Ctx:    ctx,
		Ref:    ref,
		Desc:   desc,
		Offset: offset,
		Length: length,
	}
	mock.lockFetchBlobRange.Lock()
	mock.calls.FetchBlobRange = append(mock.calls.FetchBlobRange, callInfo)
	mock.lockFetchBlobRange.Unlock()
	return mock.FetchBlobRangeFunc(ctx, ref, desc, offset, length)
}

// FetchBlobRangeCalls gets all the calls that were made to FetchBlobRange.
// Check the length with:
//
//	len(mockedClient.FetchBlobRangeCalls())
func (mock *ClientMock) FetchBlobRangeCalls() []struct {
	Ctx    context.Context
	Ref    string
	Desc   ocispec.Descriptor
	Offset int64
	Length int64
} {
	var calls []struct {
		Ctx    context.Context
		Ref    string
		Desc   ocispec.Descriptor
		Offset int64
		Length int64
	}
	mock.lockFetchBlobRange.RLock()
	calls = mock.calls.FetchBlobRange
	mock.lockFetchBlobRange.RUnlock()
	return calls
}

// FetchManifest calls FetchManifestFunc.
func (mock *ClientMock) FetchManifest(ctx context.Context, ref string) ([]byte, ocispec.Descriptor, error) {
	if mock.FetchManifestFunc == nil {
		panic("ClientMock.FetchManifestFunc: method is nil but Client.FetchManifest was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockFetchManifest.Lock()
	mock.calls.FetchManifest = append(mock.calls.FetchManifest, callInfo)
	mock.lockFetchManifest.Unlock()
	return mock.FetchManifestFunc(ctx, ref)
}

// FetchManifestCalls gets all the calls that were made to FetchManifest.
// Check the length with:
//
//	len(mockedClient.FetchManifestCalls())
func (mock *ClientMock) FetchManifestCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockFetchManifest.RLock()
	calls = mock.calls.FetchManifest
	mock.lockFetchManifest.RUnlock()
	return calls
}

// ListReferrers calls ListReferrersFunc.
func (mock *ClientMock) ListReferrers(ctx context.Context, ref string, subjectDigest string, artifactType string) ([]ocispec.Descriptor, error) {
	if mock.ListReferrersFunc == nil {
		panic("ClientMock.ListReferrersFunc: method is nil but Client.ListReferrers was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		Ref           string
		SubjectDigest string
		ArtifactType  string
	}{
		Ctx:           ctx,
		Ref:           ref,
		SubjectDigest: subjectDigest,
		ArtifactType:  artifactType,
	}
	mock.lockListReferrers.Lock()
	mock.calls.ListReferrers = append(mock.calls.ListReferrers, callInfo)
	mock.lockListReferrers.Unlock()
	return mock.ListReferrersFunc(ctx, ref, subjectDigest, artifactType)
}

// ListReferrersCalls gets all the calls that were made to ListReferrers.
// Check the length with:
//
//	len(mockedClient.ListReferrersCalls())
func (mock *ClientMock) ListReferrersCalls() []struct {
	Ctx           context.Context
	Ref           string
	SubjectDigest string
	ArtifactType  string
} {
	var calls []struct {
		Ctx           context.Context
		Ref           string
		SubjectDigest string
		ArtifactType  string
	}
	mock.lockListReferrers.RLock()
	calls = mock.calls.ListReferrers
	mock.lockListReferrers.RUnlock()
	return calls
}

// PushBlob calls PushBlobFunc.
func (mock *ClientMock) PushBlob(ctx context.Context, ref string, desc ocispec.Descriptor, content io.Reader) error {
	if mock.PushBlobFunc == nil {
		panic("ClientMock.PushBlobFunc: method is nil but Client.PushBlob was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Ref     string
		Desc    ocispec.Descriptor
		Content io.Reader
	}{
		Ctx:     ctx,
		Ref:     ref,
		Desc:    desc,
		Content: content,
	}
	mock.lockPushBlob.Lock()
	mock.calls.PushBlob = append(mock.calls.PushBlob, callInfo)
	mock.lockPushBlob.Unlock()
	return mock.PushBlobFunc(ctx, ref, desc, content)
}

// PushBlobCalls gets all the calls that were made to PushBlob.
// Check the length with:
//
//	len(mockedClient.PushBlobCalls())
func (mock *ClientMock) PushBlobCalls() []struct {
	Ctx     context.Context
	Ref     string
	Desc    ocispec.Descriptor
	Content io.Reader
} {
	var calls []struct {
		Ctx     context.Context
		Ref     string
		Desc    ocispec.Descriptor
		Content io.Reader
	}
	mock.lockPushBlob.RLock()
	calls = mock.calls.PushBlob
	mock.lockPushBlob.RUnlock()
	return calls
}

// PushManifest calls PushManifestFunc.
func (mock *ClientMock) PushManifest(ctx context.Context, ref string, desc ocispec.Descriptor, content []byte) error {
	if mock.PushManifestFunc == nil {
		panic("ClientMock.PushManifestFunc: method is nil but Client.PushManifest was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Ref     string
		Desc    ocispec.Descriptor
		Content []byte
	}{
		Ctx:     ctx,
		Ref:     ref,
		Desc:    desc,
		Content: content,
	}
	mock.lockPushManifest.Lock()
	mock.calls.PushManifest = append(mock.calls.PushManifest, callInfo)
	mock.lockPushManifest.Unlock()
	return mock.PushManifestFunc(ctx, ref, desc, content)
}

// PushManifestCalls gets all the calls that were made to PushManifest.
// Check the length with:
//
//	len(mockedClient.PushManifestCalls())
func (mock *ClientMock) PushManifestCalls() []struct {
	Ctx     context.Context
	Ref     string
	Desc    ocispec.Descriptor
	Content []byte
} {
	var calls []struct {
		Ctx     context.Context
		Ref     string
		Desc    ocispec.Descriptor
		Content []byte
	}
	mock.lockPushManifest.RLock()
	calls = mock.calls.PushManifest
	mock.lockPushManifest.RUnlock()
	return calls
}

// PushReferrer calls PushReferrerFunc.
func (mock *ClientMock) PushReferrer(ctx context.Context, ref string, subject ocispec.Descriptor, artifact ocispec.Descriptor, content []byte) (digest.Digest, error) {
	if mock.PushReferrerFunc == nil {
		panic("ClientMock.PushReferrerFunc: method is nil but Client.PushReferrer was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Ref      string
		Subject  ocispec.Descriptor
		Artifact ocispec.Descriptor
		Content  []byte
	}{
		Ctx:      ctx,
		Ref:      ref,
		Subject:  subject,
		Artifact: artifact,
		Content:  content,
	}
	mock.lockPushReferrer.Lock()
	mock.calls.PushReferrer = append(mock.calls.PushReferrer, callInfo)
	mock.lockPushReferrer.Unlock()
	return mock.PushReferrerFunc(ctx, ref, subject, artifact, content)
}

// PushReferrerCalls gets all the calls that were made to PushReferrer.
// Check the length with:
//
//	len(mockedClient.PushReferrerCalls())
func (mock *ClientMock) PushReferrerCalls() []struct {
	Ctx      context.Context
	Ref      string
	Subject  ocispec.Descriptor
	Artifact ocispec.Descriptor
	Content  []byte
} {
	var calls []struct {
		Ctx      context.Context
		Ref      string
		Subject  ocispec.Descriptor
		Artifact ocispec.Descriptor
		Content  []byte
	}
	mock.lockPushReferrer.RLock()
	calls = mock.calls.PushReferrer
	mock.lockPushReferrer.RUnlock()
	return calls
}

// ResolveManifest calls ResolveManifestFunc.
func (mock *ClientMock) ResolveManifest(ctx context.Context, ref string) (ocispec.Descriptor, error) {
	if mock.ResolveManifestFunc == nil {
		panic("ClientMock.ResolveManifestFunc: method is nil but Client.ResolveManifest was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockResolveManifest.Lock()
	mock.calls.ResolveManifest = append(mock.calls.ResolveManifest, callInfo)
	mock.lockResolveManifest.Unlock()
	return mock.ResolveManifestFunc(ctx, ref)
}

// ResolveManifestCalls gets all the calls that were made to ResolveManifest.
// Check the length with:
//
//	len(mockedClient.ResolveManifestCalls())
func (mock *ClientMock) ResolveManifestCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockResolveManifest.RLock()
	calls = mock.calls.ResolveManifest
	mock.lockResolveManifest.RUnlock()
	return calls
}

// Tag calls TagFunc.
func (mock *ClientMock) Tag(ctx context.Context, ref string, desc ocispec.Descriptor, tag string) error {
	if mock.TagFunc == nil {
		panic("ClientMock.TagFunc: method is nil but Client.Tag was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Ref  string
		Desc ocispec.Descriptor
		Tag  string
	}{
		Ctx:  ctx,
		Ref:  ref,
		Desc: desc,
		Tag:  tag,
	}
	mock.lockTag.Lock()
	mock.calls.Tag = append(mock.calls.Tag, callInfo)
	mock.lockTag.Unlock()
	return mock.TagFunc(ctx, ref, desc, tag)
}

// TagCalls gets all the calls that were made to Tag.
// Check the length with:
//
//	len(mockedClient.TagCalls())
func (mock *ClientMock) TagCalls() []struct {
	Ctx  context.Context
	Ref  string
	Desc ocispec.Descriptor
	Tag  string
} {
	var calls []struct {
		Ctx  context.Context
		Ref  string
		Desc ocispec.Descriptor
		Tag  string
	}
	mock.lockTag.RLock()
	calls = mock.calls.Tag
	mock.lockTag.RUnlock()
	return calls
}
