// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/meigma/blobber/v2/internal/estargz"
	"io"
	"io/fs"
	"sync"
)

// Ensure, that BuilderMock does implement estargz.Builder.
// If this is not the case, regenerate this file with moq.
var _ estargz.Builder = &BuilderMock{}

// BuilderMock is a mock implementation of estargz.Builder.
//
//	func TestSomethingThatUsesBuilder(t *testing.T) {
//
//		// make and configure a mocked estargz.Builder
//		mockedBuilder := &BuilderMock{
//			BuildFunc: func(ctx context.Context, dst io.Writer, src fs.FS) (*estargz.BuildResult, error) {
//				panic("mock out the Build method")
//			},
//		}
//
//		// use mockedBuilder in code that requires estargz.Builder
//		// and then make assertions.
//
//	}
type BuilderMock struct {
	// BuildFunc mocks the Build method.
	BuildFunc func(ctx context.Context, dst io.Writer, src fs.FS) (*estargz.BuildResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Build holds details about calls to the Build method.
		Build []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dst is the dst argument value.
			Dst io.Writer
			// Src is the src argument value.
			Src fs.FS
		}
	}
	lockBuild sync.RWMutex
}

// Build calls BuildFunc.
func (mock *BuilderMock) Build(ctx context.Context, dst io.Writer, src fs.FS) (*estargz.BuildResult, error) {
	if mock.BuildFunc == nil {
		panic("BuilderMock.BuildFunc: method is nil but Builder.Build was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Dst io.Writer
		Src fs.FS
	}{
		Ctx: ctx,
		Dst: dst,
		Src: src,
	}
	mock.lockBuild.Lock()
	mock.calls.Build = append(mock.calls.Build, callInfo)
	mock.lockBuild.Unlock()
	return mock.BuildFunc(ctx, dst, src)
}

// BuildCalls gets all the calls that were made to Build.
// Check the length with:
//
//	len(mockedBuilder.BuildCalls())
func (mock *BuilderMock) BuildCalls() []struct {
	Ctx context.Context
	Dst io.Writer
	Src fs.FS
} {
	var calls []struct {
		Ctx context.Context
		Dst io.Writer
		Src fs.FS
	}
	mock.lockBuild.RLock()
	calls = mock.calls.Build
	mock.lockBuild.RUnlock()
	return calls
}
