// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/meigma/blobber/v2/internal/estargz"
	"io/fs"
	"sync"
)

// Ensure, that ReaderMock does implement estargz.Reader.
// If this is not the case, regenerate this file with moq.
var _ estargz.Reader = &ReaderMock{}

// ReaderMock is a mock implementation of estargz.Reader.
//
//	func TestSomethingThatUsesReader(t *testing.T) {
//
//		// make and configure a mocked estargz.Reader
//		mockedReader := &ReaderMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			OpenFunc: func(name string) (fs.File, error) {
//				panic("mock out the Open method")
//			},
//			ReadDirFunc: func(name string) ([]fs.DirEntry, error) {
//				panic("mock out the ReadDir method")
//			},
//			StatFunc: func(name string) (fs.FileInfo, error) {
//				panic("mock out the Stat method")
//			},
//		}
//
//		// use mockedReader in code that requires estargz.Reader
//		// and then make assertions.
//
//	}
type ReaderMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// OpenFunc mocks the Open method.
	OpenFunc func(name string) (fs.File, error)

	// ReadDirFunc mocks the ReadDir method.
	ReadDirFunc func(name string) ([]fs.DirEntry, error)

	// StatFunc mocks the Stat method.
	StatFunc func(name string) (fs.FileInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Open holds details about calls to the Open method.
		Open []struct {
			// Name is the name argument value.
			Name string
		}
		// ReadDir holds details about calls to the ReadDir method.
		ReadDir []struct {
			// Name is the name argument value.
			Name string
		}
		// Stat holds details about calls to the Stat method.
		Stat []struct {
			// Name is the name argument value.
			Name string
		}
	}
	lockClose   sync.RWMutex
	lockOpen    sync.RWMutex
	lockReadDir sync.RWMutex
	lockStat    sync.RWMutex
}

// Close calls CloseFunc.
func (mock *ReaderMock) Close() error {
	if mock.CloseFunc == nil {
		panic("ReaderMock.CloseFunc: method is nil but Reader.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedReader.CloseCalls())
func (mock *ReaderMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Open calls OpenFunc.
func (mock *ReaderMock) Open(name string) (fs.File, error) {
	if mock.OpenFunc == nil {
		panic("ReaderMock.OpenFunc: method is nil but Reader.Open was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	return mock.OpenFunc(name)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedReader.OpenCalls())
func (mock *ReaderMock) OpenCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}

// ReadDir calls ReadDirFunc.
func (mock *ReaderMock) ReadDir(name string) ([]fs.DirEntry, error) {
	if mock.ReadDirFunc == nil {
		panic("ReaderMock.ReadDirFunc: method is nil but Reader.ReadDir was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockReadDir.Lock()
	mock.calls.ReadDir = append(mock.calls.ReadDir, callInfo)
	mock.lockReadDir.Unlock()
	return mock.ReadDirFunc(name)
}

// ReadDirCalls gets all the calls that were made to ReadDir.
// Check the length with:
//
//	len(mockedReader.ReadDirCalls())
func (mock *ReaderMock) ReadDirCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockReadDir.RLock()
	calls = mock.calls.ReadDir
	mock.lockReadDir.RUnlock()
	return calls
}

// Stat calls StatFunc.
func (mock *ReaderMock) Stat(name string) (fs.FileInfo, error) {
	if mock.StatFunc == nil {
		panic("ReaderMock.StatFunc: method is nil but Reader.Stat was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockStat.Lock()
	mock.calls.Stat = append(mock.calls.Stat, callInfo)
	mock.lockStat.Unlock()
	return mock.StatFunc(name)
}

// StatCalls gets all the calls that were made to Stat.
// Check the length with:
//
//	len(mockedReader.StatCalls())
func (mock *ReaderMock) StatCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockStat.RLock()
	calls = mock.calls.Stat
	mock.lockStat.RUnlock()
	return calls
}
