// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/meigma/blobber/v2/internal/cache"
	"github.com/opencontainers/go-digest"
	"io/fs"
	"sync"
)

// Ensure, that FileCacheMock does implement cache.FileCache.
// If this is not the case, regenerate this file with moq.
var _ cache.FileCache = &FileCacheMock{}

// FileCacheMock is a mock implementation of cache.FileCache.
//
//	func TestSomethingThatUsesFileCache(t *testing.T) {
//
//		// make and configure a mocked cache.FileCache
//		mockedFileCache := &FileCacheMock{
//			DirFunc: func(d digest.Digest) (string, error) {
//				panic("mock out the Dir method")
//			},
//			GetFunc: func(d digest.Digest, path string) (fs.File, error) {
//				panic("mock out the Get method")
//			},
//			IsCompleteFunc: func(d digest.Digest) bool {
//				panic("mock out the IsComplete method")
//			},
//			MarkCompleteFunc: func(d digest.Digest, size int64) error {
//				panic("mock out the MarkComplete method")
//			},
//			TouchAccessFunc: func(d digest.Digest) error {
//				panic("mock out the TouchAccess method")
//			},
//			WrapFileFunc: func(d digest.Digest, path string, f fs.File, size int64, checksum string) fs.File {
//				panic("mock out the WrapFile method")
//			},
//		}
//
//		// use mockedFileCache in code that requires cache.FileCache
//		// and then make assertions.
//
//	}
type FileCacheMock struct {
	// DirFunc mocks the Dir method.
	DirFunc func(d digest.Digest) (string, error)

	// GetFunc mocks the Get method.
	GetFunc func(d digest.Digest, path string) (fs.File, error)

	// IsCompleteFunc mocks the IsComplete method.
	IsCompleteFunc func(d digest.Digest) bool

	// MarkCompleteFunc mocks the MarkComplete method.
	MarkCompleteFunc func(d digest.Digest, size int64) error

	// TouchAccessFunc mocks the TouchAccess method.
	TouchAccessFunc func(d digest.Digest) error

	// WrapFileFunc mocks the WrapFile method.
	WrapFileFunc func(d digest.Digest, path string, f fs.File, size int64, checksum string) fs.File

	// calls tracks calls to the methods.
	calls struct {
		// Dir holds details about calls to the Dir method.
		Dir []struct {
			// D is the d argument value.
			D digest.Digest
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// D is the d argument value.
			D digest.Digest
			// Path is the path argument value.
			Path string
		}
		// IsComplete holds details about calls to the IsComplete method.
		IsComplete []struct {
			// D is the d argument value.
			D digest.Digest
		}
		// MarkComplete holds details about calls to the MarkComplete method.
		MarkComplete []struct {
			// D is the d argument value.
			D digest.Digest
			// Size is the size argument value.
			Size int64
		}
		// TouchAccess holds details about calls to the TouchAccess method.
		TouchAccess []struct {
			// D is the d argument value.
			D digest.Digest
		}
		// WrapFile holds details about calls to the WrapFile method.
		WrapFile []struct {
			// D is the d argument value.
			D digest.Digest
			// Path is the path argument value.
			Path string
			// F is the f argument value.
			F fs.File
			// Size is the size argument value.
			Size int64
			// Checksum is the checksum argument value.
			Checksum string
		}
	}
	lockDir          sync.RWMutex
	lockGet          sync.RWMutex
	lockIsComplete   sync.RWMutex
	lockMarkComplete sync.RWMutex
	lockTouchAccess  sync.RWMutex
	lockWrapFile     sync.RWMutex
}

// Dir calls DirFunc.
func (mock *FileCacheMock) Dir(d digest.Digest) (string, error) {
	if mock.DirFunc == nil {
		panic("FileCacheMock.DirFunc: method is nil but FileCache.Dir was just called")
	}
	callInfo := struct {
		D digest.Digest
	}{
		D: d,
	}
	mock.lockDir.Lock()
	mock.calls.Dir = append(mock.calls.Dir, callInfo)
	mock.lockDir.Unlock()
	return mock.DirFunc(d)
}

// DirCalls gets all the calls that were made to Dir.
// Check the length with:
//
//	len(mockedFileCache.DirCalls())
func (mock *FileCacheMock) DirCalls() []struct {
	D digest.Digest
} {
	var calls []struct {
		D digest.Digest
	}
	mock.lockDir.RLock()
	calls = mock.calls.Dir
	mock.lockDir.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *FileCacheMock) Get(d digest.Digest, path string) (fs.File, error) {
	if mock.GetFunc == nil {
		panic("FileCacheMock.GetFunc: method is nil but FileCache.Get was just called")
	}
	callInfo := struct {
		D    digest.Digest
		Path string
	}{
		D:    d,
		Path: path,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(d, path)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedFileCache.GetCalls())
func (mock *FileCacheMock) GetCalls() []struct {
	D    digest.Digest
	Path string
} {
	var calls []struct {
		D    digest.Digest
		Path string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// IsComplete calls IsCompleteFunc.
func (mock *FileCacheMock) IsComplete(d digest.Digest) bool {
	if mock.IsCompleteFunc == nil {
		panic("FileCacheMock.IsCompleteFunc: method is nil but FileCache.IsComplete was just called")
	}
	callInfo := struct {
		D digest.Digest
	}{
		D: d,
	}
	mock.lockIsComplete.Lock()
	mock.calls.IsComplete = append(mock.calls.IsComplete, callInfo)
	mock.lockIsComplete.Unlock()
	return mock.IsCompleteFunc(d)
}

// IsCompleteCalls gets all the calls that were made to IsComplete.
// Check the length with:
//
//	len(mockedFileCache.IsCompleteCalls())
func (mock *FileCacheMock) IsCompleteCalls() []struct {
	D digest.Digest
} {
	var calls []struct {
		D digest.Digest
	}
	mock.lockIsComplete.RLock()
	calls = mock.calls.IsComplete
	mock.lockIsComplete.RUnlock()
	return calls
}

// MarkComplete calls MarkCompleteFunc.
func (mock *FileCacheMock) MarkComplete(d digest.Digest, size int64) error {
	if mock.MarkCompleteFunc == nil {
		panic("FileCacheMock.MarkCompleteFunc: method is nil but FileCache.MarkComplete was just called")
	}
	callInfo := struct {
		D    digest.Digest
		Size int64
	}{
		D:    d,
		Size: size,
	}
	mock.lockMarkComplete.Lock()
	mock.calls.MarkComplete = append(mock.calls.MarkComplete, callInfo)
	mock.lockMarkComplete.Unlock()
	return mock.MarkCompleteFunc(d, size)
}

// MarkCompleteCalls gets all the calls that were made to MarkComplete.
// Check the length with:
//
//	len(mockedFileCache.MarkCompleteCalls())
func (mock *FileCacheMock) MarkCompleteCalls() []struct {
	D    digest.Digest
	Size int64
} {
	var calls []struct {
		D    digest.Digest
		Size int64
	}
	mock.lockMarkComplete.RLock()
	calls = mock.calls.MarkComplete
	mock.lockMarkComplete.RUnlock()
	return calls
}

// TouchAccess calls TouchAccessFunc.
func (mock *FileCacheMock) TouchAccess(d digest.Digest) error {
	if mock.TouchAccessFunc == nil {
		panic("FileCacheMock.TouchAccessFunc: method is nil but FileCache.TouchAccess was just called")
	}
	callInfo := struct {
		D digest.Digest
	}{
		D: d,
	}
	mock.lockTouchAccess.Lock()
	mock.calls.TouchAccess = append(mock.calls.TouchAccess, callInfo)
	mock.lockTouchAccess.Unlock()
	return mock.TouchAccessFunc(d)
}

// TouchAccessCalls gets all the calls that were made to TouchAccess.
// Check the length with:
//
//	len(mockedFileCache.TouchAccessCalls())
func (mock *FileCacheMock) TouchAccessCalls() []struct {
	D digest.Digest
} {
	var calls []struct {
		D digest.Digest
	}
	mock.lockTouchAccess.RLock()
	calls = mock.calls.TouchAccess
	mock.lockTouchAccess.RUnlock()
	return calls
}

// WrapFile calls WrapFileFunc.
func (mock *FileCacheMock) WrapFile(d digest.Digest, path string, f fs.File, size int64, checksum string) fs.File {
	if mock.WrapFileFunc == nil {
		panic("FileCacheMock.WrapFileFunc: method is nil but FileCache.WrapFile was just called")
	}
	callInfo := struct {
		D        digest.Digest
		Path     string
		F        fs.File
		Size     int64
		Checksum string
	}{
		D:        d,
		Path:     path,
		F:        f,
		Size:     size,
		Checksum: checksum,
	}
	mock.lockWrapFile.Lock()
	mock.calls.WrapFile = append(mock.calls.WrapFile, callInfo)
	mock.lockWrapFile.Unlock()
	return mock.WrapFileFunc(d, path, f, size, checksum)
}

// WrapFileCalls gets all the calls that were made to WrapFile.
// Check the length with:
//
//	len(mockedFileCache.WrapFileCalls())
func (mock *FileCacheMock) WrapFileCalls() []struct {
	D        digest.Digest
	Path     string
	F        fs.File
	Size     int64
	Checksum string
} {
	var calls []struct {
		D        digest.Digest
		Path     string
		F        fs.File
		Size     int64
		Checksum string
	}
	mock.lockWrapFile.RLock()
	calls = mock.calls.WrapFile
	mock.lockWrapFile.RUnlock()
	return calls
}
