// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/meigma/blobber/v2/internal/cache"
	"github.com/opencontainers/go-digest"
	"sync"
)

// Ensure, that RefCacheMock does implement cache.RefCache.
// If this is not the case, regenerate this file with moq.
var _ cache.RefCache = &RefCacheMock{}

// RefCacheMock is a mock implementation of cache.RefCache.
//
//	func TestSomethingThatUsesRefCache(t *testing.T) {
//
//		// make and configure a mocked cache.RefCache
//		mockedRefCache := &RefCacheMock{
//			LookupFunc: func(ref string) (digest.Digest, bool) {
//				panic("mock out the Lookup method")
//			},
//			StoreFunc: func(ref string, d digest.Digest)  {
//				panic("mock out the Store method")
//			},
//		}
//
//		// use mockedRefCache in code that requires cache.RefCache
//		// and then make assertions.
//
//	}
type RefCacheMock struct {
	// LookupFunc mocks the Lookup method.
	LookupFunc func(ref string) (digest.Digest, bool)

	// StoreFunc mocks the Store method.
	StoreFunc func(ref string, d digest.Digest)

	// calls tracks calls to the methods.
	calls struct {
		// Lookup holds details about calls to the Lookup method.
		Lookup []struct {
			// Ref is the ref argument value.
			Ref string
		}
		// Store holds details about calls to the Store method.
		Store []struct {
			// Ref is the ref argument value.
			Ref string
			// D is the d argument value.
			D digest.Digest
		}
	}
	lockLookup sync.RWMutex
	lockStore  sync.RWMutex
}

// Lookup calls LookupFunc.
func (mock *RefCacheMock) Lookup(ref string) (digest.Digest, bool) {
	if mock.LookupFunc == nil {
		panic("RefCacheMock.LookupFunc: method is nil but RefCache.Lookup was just called")
	}
	callInfo := struct {
		Ref string
	}{
		Ref: ref,
	}
	mock.lockLookup.Lock()
	mock.calls.Lookup = append(mock.calls.Lookup, callInfo)
	mock.lockLookup.Unlock()
	return mock.LookupFunc(ref)
}

// LookupCalls gets all the calls that were made to Lookup.
// Check the length with:
//
//	len(mockedRefCache.LookupCalls())
func (mock *RefCacheMock) LookupCalls() []struct {
	Ref string
} {
	var calls []struct {
		Ref string
	}
	mock.lockLookup.RLock()
	calls = mock.calls.Lookup
	mock.lockLookup.RUnlock()
	return calls
}

// Store calls StoreFunc.
func (mock *RefCacheMock) Store(ref string, d digest.Digest) {
	if mock.StoreFunc == nil {
		panic("RefCacheMock.StoreFunc: method is nil but RefCache.Store was just called")
	}
	callInfo := struct {
		Ref string
		D   digest.Digest
	}{
		Ref: ref,
		D:   d,
	}
	mock.lockStore.Lock()
	mock.calls.Store = append(mock.calls.Store, callInfo)
	mock.lockStore.Unlock()
	mock.StoreFunc(ref, d)
}

// StoreCalls gets all the calls that were made to Store.
// Check the length with:
//
//	len(mockedRefCache.StoreCalls())
func (mock *RefCacheMock) StoreCalls() []struct {
	Ref string
	D   digest.Digest
} {
	var calls []struct {
		Ref string
		D   digest.Digest
	}
	mock.lockStore.RLock()
	calls = mock.calls.Store
	mock.lockStore.RUnlock()
	return calls
}
