// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/meigma/blobber/v2/internal/estargz"
	"github.com/meigma/blobber/v2/internal/registry"
	"github.com/opencontainers/go-digest"
	"io"
	"sync"
)

// Ensure, that RegistryMock does implement registry.Registry.
// If this is not the case, regenerate this file with moq.
var _ registry.Registry = &RegistryMock{}

// RegistryMock is a mock implementation of registry.Registry.
//
//	func TestSomethingThatUsesRegistry(t *testing.T) {
//
//		// make and configure a mocked registry.Registry
//		mockedRegistry := &RegistryMock{
//			AttachArtifactFunc: func(ctx context.Context, ref string, artifactType string, content []byte, annotations map[string]string) (digest.Digest, error) {
//				panic("mock out the AttachArtifact method")
//			},
//			FetchBlobFunc: func(ctx context.Context, ref string) (io.ReadCloser, error) {
//				panic("mock out the FetchBlob method")
//			},
//			FetchBlobByDigestFunc: func(ctx context.Context, ref string, d digest.Digest, size int64) (io.ReadCloser, error) {
//				panic("mock out the FetchBlobByDigest method")
//			},
//			FetchManifestFunc: func(ctx context.Context, ref string, opts ...registry.FetchOption) (*registry.BlobManifest, error) {
//				panic("mock out the FetchManifest method")
//			},
//			FetchReferrerContentFunc: func(ctx context.Context, ref string, referrerDigest digest.Digest) ([]byte, error) {
//				panic("mock out the FetchReferrerContent method")
//			},
//			OpenBlobFunc: func(ctx context.Context, ref string) (estargz.BlobSource, error) {
//				panic("mock out the OpenBlob method")
//			},
//			OpenBlobByDigestFunc: func(ctx context.Context, ref string, d digest.Digest, size int64) (estargz.BlobSource, error) {
//				panic("mock out the OpenBlobByDigest method")
//			},
//			PushFunc: func(ctx context.Context, ref string, blob io.Reader, metadata registry.PushMetadata) (*registry.PushResult, error) {
//				panic("mock out the Push method")
//			},
//			ResolveRefFunc: func(ctx context.Context, ref string) (digest.Digest, error) {
//				panic("mock out the ResolveRef method")
//			},
//		}
//
//		// use mockedRegistry in code that requires registry.Registry
//		// and then make assertions.
//
//	}
type RegistryMock struct {
	// AttachArtifactFunc mocks the AttachArtifact method.
	AttachArtifactFunc func(ctx context.Context, ref string, artifactType string, content []byte, annotations map[string]string) (digest.Digest, error)

	// FetchBlobFunc mocks the FetchBlob method.
	FetchBlobFunc func(ctx context.Context, ref string) (io.ReadCloser, error)

	// FetchBlobByDigestFunc mocks the FetchBlobByDigest method.
	FetchBlobByDigestFunc func(ctx context.Context, ref string, d digest.Digest, size int64) (io.ReadCloser, error)

	// FetchManifestFunc mocks the FetchManifest method.
	FetchManifestFunc func(ctx context.Context, ref string, opts ...registry.FetchOption) (*registry.BlobManifest, error)

	// FetchReferrerContentFunc mocks the FetchReferrerContent method.
	FetchReferrerContentFunc func(ctx context.Context, ref string, referrerDigest digest.Digest) ([]byte, error)

	// OpenBlobFunc mocks the OpenBlob method.
	OpenBlobFunc func(ctx context.Context, ref string) (estargz.BlobSource, error)

	// OpenBlobByDigestFunc mocks the OpenBlobByDigest method.
	OpenBlobByDigestFunc func(ctx context.Context, ref string, d digest.Digest, size int64) (estargz.BlobSource, error)

	// PushFunc mocks the Push method.
	PushFunc func(ctx context.Context, ref string, blob io.Reader, metadata registry.PushMetadata) (*registry.PushResult, error)

	// ResolveRefFunc mocks the ResolveRef method.
	ResolveRefFunc func(ctx context.Context, ref string) (digest.Digest, error)

	// calls tracks calls to the methods.
	calls struct {
		// AttachArtifact holds details about calls to the AttachArtifact method.
		AttachArtifact []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// ArtifactType is the artifactType argument value.
			ArtifactType string
			// Content is the content argument value.
			Content []byte
			// Annotations is the annotations argument value.
			Annotations map[string]string
		}
		// FetchBlob holds details about calls to the FetchBlob method.
		FetchBlob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
		// FetchBlobByDigest holds details about calls to the FetchBlobByDigest method.
		FetchBlobByDigest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// D is the d argument value.
			D digest.Digest
			// Size is the size argument value.
			Size int64
		}
		// FetchManifest holds details about calls to the FetchManifest method.
		FetchManifest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Opts is the opts argument value.
			Opts []registry.FetchOption
		}
		// FetchReferrerContent holds details about calls to the FetchReferrerContent method.
		FetchReferrerContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// ReferrerDigest is the referrerDigest argument value.
			ReferrerDigest digest.Digest
		}
		// OpenBlob holds details about calls to the OpenBlob method.
		OpenBlob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
		// OpenBlobByDigest holds details about calls to the OpenBlobByDigest method.
		OpenBlobByDigest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// D is the d argument value.
			D digest.Digest
			// Size is the size argument value.
			Size int64
		}
		// Push holds details about calls to the Push method.
		Push []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Blob is the blob argument value.
			Blob io.Reader
			// Metadata is the metadata argument value.
			Metadata registry.PushMetadata
		}
		// ResolveRef holds details about calls to the ResolveRef method.
		ResolveRef []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
	}
	lockAttachArtifact       sync.RWMutex
	lockFetchBlob            sync.RWMutex
	lockFetchBlobByDigest    sync.RWMutex
	lockFetchManifest        sync.RWMutex
	lockFetchReferrerContent sync.RWMutex
	lockOpenBlob             sync.RWMutex
	lockOpenBlobByDigest     sync.RWMutex
	lockPush                 sync.RWMutex
	lockResolveRef           sync.RWMutex
}

// AttachArtifact calls AttachArtifactFunc.
func (mock *RegistryMock) AttachArtifact(ctx context.Context, ref string, artifactType string, content []byte, annotations map[string]string) (digest.Digest, error) {
	if mock.AttachArtifactFunc == nil {
		panic("RegistryMock.AttachArtifactFunc: method is nil but Registry.AttachArtifact was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Ref          string
		ArtifactType string
		Content      []byte
		Annotations  map[string]string
	}{
		Ctx:          ctx,
		Ref:          ref,
		ArtifactType: artifactType,
		Content:      content,
		Annotations:  annotations,
	}
	mock.lockAttachArtifact.Lock()
	mock.calls.AttachArtifact = append(mock.calls.AttachArtifact, callInfo)
	mock.lockAttachArtifact.Unlock()
	return mock.AttachArtifactFunc(ctx, ref, artifactType, content, annotations)
}

// AttachArtifactCalls gets all the calls that were made to AttachArtifact.
// Check the length with:
//
//	len(mockedRegistry.AttachArtifactCalls())
func (mock *RegistryMock) AttachArtifactCalls() []struct {
	Ctx          context.Context
	Ref          string
	ArtifactType string
	Content      []byte
	Annotations  map[string]string
} {
	var calls []struct {
		Ctx          context.Context
		Ref          string
		ArtifactType string
		Content      []byte
		Annotations  map[string]string
	}
	mock.lockAttachArtifact.RLock()
	calls = mock.calls.AttachArtifact
	mock.lockAttachArtifact.RUnlock()
	return calls
}

// FetchBlob calls FetchBlobFunc.
func (mock *RegistryMock) FetchBlob(ctx context.Context, ref string) (io.ReadCloser, error) {
	if mock.FetchBlobFunc == nil {
		panic("RegistryMock.FetchBlobFunc: method is nil but Registry.FetchBlob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockFetchBlob.Lock()
	mock.calls.FetchBlob = append(mock.calls.FetchBlob, callInfo)
	mock.lockFetchBlob.Unlock()
	return mock.FetchBlobFunc(ctx, ref)
}

// FetchBlobCalls gets all the calls that were made to FetchBlob.
// Check the length with:
//
//	len(mockedRegistry.FetchBlobCalls())
func (mock *RegistryMock) FetchBlobCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockFetchBlob.RLock()
	calls = mock.calls.FetchBlob
	mock.lockFetchBlob.RUnlock()
	return calls
}

// FetchBlobByDigest calls FetchBlobByDigestFunc.
func (mock *RegistryMock) FetchBlobByDigest(ctx context.Context, ref string, d digest.Digest, size int64) (io.ReadCloser, error) {
	if mock.FetchBlobByDigestFunc == nil {
		panic("RegistryMock.FetchBlobByDigestFunc: method is nil but Registry.FetchBlobByDigest was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Ref  string
		D    digest.Digest
		Size int64
	}{
		Ctx:  ctx,
		Ref:  ref,
		D:    d,
		Size: size,
	}
	mock.lockFetchBlobByDigest.Lock()
	mock.calls.FetchBlobByDigest = append(mock.calls.FetchBlobByDigest, callInfo)
	mock.lockFetchBlobByDigest.Unlock()
	return mock.FetchBlobByDigestFunc(ctx, ref, d, size)
}

// FetchBlobByDigestCalls gets all the calls that were made to FetchBlobByDigest.
// Check the length with:
//
//	len(mockedRegistry.FetchBlobByDigestCalls())
func (mock *RegistryMock) FetchBlobByDigestCalls() []struct {
	Ctx  context.Context
	Ref  string
	D    digest.Digest
	Size int64
} {
	var calls []struct {
		Ctx  context.Context
		Ref  string
		D    digest.Digest
		Size int64
	}
	mock.lockFetchBlobByDigest.RLock()
	calls = mock.calls.FetchBlobByDigest
	mock.lockFetchBlobByDigest.RUnlock()
	return calls
}

// FetchManifest calls FetchManifestFunc.
func (mock *RegistryMock) FetchManifest(ctx context.Context, ref string, opts ...registry.FetchOption) (*registry.BlobManifest, error) {
	if mock.FetchManifestFunc == nil {
		panic("RegistryMock.FetchManifestFunc: method is nil but Registry.FetchManifest was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Ref  string
		Opts []registry.FetchOption
	}{
		Ctx:  ctx,
		Ref:  ref,
		Opts: opts,
	}
	mock.lockFetchManifest.Lock()
	mock.calls.FetchManifest = append(mock.calls.FetchManifest, callInfo)
	mock.lockFetchManifest.Unlock()
	return mock.FetchManifestFunc(ctx, ref, opts...)
}

// FetchManifestCalls gets all the calls that were made to FetchManifest.
// Check the length with:
//
//	len(mockedRegistry.FetchManifestCalls())
func (mock *RegistryMock) FetchManifestCalls() []struct {
	Ctx  context.Context
	Ref  string
	Opts []registry.FetchOption
} {
	var calls []struct {
		Ctx  context.Context
		Ref  string
		Opts []registry.FetchOption
	}
	mock.lockFetchManifest.RLock()
	calls = mock.calls.FetchManifest
	mock.lockFetchManifest.RUnlock()
	return calls
}

// FetchReferrerContent calls FetchReferrerContentFunc.
func (mock *RegistryMock) FetchReferrerContent(ctx context.Context, ref string, referrerDigest digest.Digest) ([]byte, error) {
	if mock.FetchReferrerContentFunc == nil {
		panic("RegistryMock.FetchReferrerContentFunc: method is nil but Registry.FetchReferrerContent was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Ref            string
		ReferrerDigest digest.Digest
	}{
		Ctx:            ctx,
		Ref:            ref,
		ReferrerDigest: referrerDigest,
	}
	mock.lockFetchReferrerContent.Lock()
	mock.calls.FetchReferrerContent = append(mock.calls.FetchReferrerContent, callInfo)
	mock.lockFetchReferrerContent.Unlock()
	return mock.FetchReferrerContentFunc(ctx, ref, referrerDigest)
}

// FetchReferrerContentCalls gets all the calls that were made to FetchReferrerContent.
// Check the length with:
//
//	len(mockedRegistry.FetchReferrerContentCalls())
func (mock *RegistryMock) FetchReferrerContentCalls() []struct {
	Ctx            context.Context
	Ref            string
	ReferrerDigest digest.Digest
} {
	var calls []struct {
		Ctx            context.Context
		Ref            string
		ReferrerDigest digest.Digest
	}
	mock.lockFetchReferrerContent.RLock()
	calls = mock.calls.FetchReferrerContent
	mock.lockFetchReferrerContent.RUnlock()
	return calls
}

// OpenBlob calls OpenBlobFunc.
func (mock *RegistryMock) OpenBlob(ctx context.Context, ref string) (estargz.BlobSource, error) {
	if mock.OpenBlobFunc == nil {
		panic("RegistryMock.OpenBlobFunc: method is nil but Registry.OpenBlob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockOpenBlob.Lock()
	mock.calls.OpenBlob = append(mock.calls.OpenBlob, callInfo)
	mock.lockOpenBlob.Unlock()
	return mock.OpenBlobFunc(ctx, ref)
}

// OpenBlobCalls gets all the calls that were made to OpenBlob.
// Check the length with:
//
//	len(mockedRegistry.OpenBlobCalls())
func (mock *RegistryMock) OpenBlobCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockOpenBlob.RLock()
	calls = mock.calls.OpenBlob
	mock.lockOpenBlob.RUnlock()
	return calls
}

// OpenBlobByDigest calls OpenBlobByDigestFunc.
func (mock *RegistryMock) OpenBlobByDigest(ctx context.Context, ref string, d digest.Digest, size int64) (estargz.BlobSource, error) {
	if mock.OpenBlobByDigestFunc == nil {
		panic("RegistryMock.OpenBlobByDigestFunc: method is nil but Registry.OpenBlobByDigest was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Ref  string
		D    digest.Digest
		Size int64
	}{
		Ctx:  ctx,
		Ref:  ref,
		D:    d,
		Size: size,
	}
	mock.lockOpenBlobByDigest.Lock()
	mock.calls.OpenBlobByDigest = append(mock.calls.OpenBlobByDigest, callInfo)
	mock.lockOpenBlobByDigest.Unlock()
	return mock.OpenBlobByDigestFunc(ctx, ref, d, size)
}

// OpenBlobByDigestCalls gets all the calls that were made to OpenBlobByDigest.
// Check the length with:
//
//	len(mockedRegistry.OpenBlobByDigestCalls())
func (mock *RegistryMock) OpenBlobByDigestCalls() []struct {
	Ctx  context.Context
	Ref  string
	D    digest.Digest
	Size int64
} {
	var calls []struct {
		Ctx  context.Context
		Ref  string
		D    digest.Digest
		Size int64
	}
	mock.lockOpenBlobByDigest.RLock()
	calls = mock.calls.OpenBlobByDigest
	mock.lockOpenBlobByDigest.RUnlock()
	return calls
}

// Push calls PushFunc.
func (mock *RegistryMock) Push(ctx context.Context, ref string, blob io.Reader, metadata registry.PushMetadata) (*registry.PushResult, error) {
	if mock.PushFunc == nil {
		panic("RegistryMock.PushFunc: method is nil but Registry.Push was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Ref      string
		Blob     io.Reader
		Metadata registry.PushMetadata
	}{
		Ctx:      ctx,
		Ref:      ref,
		Blob:     blob,
		Metadata: metadata,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(ctx, ref, blob, metadata)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedRegistry.PushCalls())
func (mock *RegistryMock) PushCalls() []struct {
	Ctx      context.Context
	Ref      string
	Blob     io.Reader
	Metadata registry.PushMetadata
} {
	var calls []struct {
		Ctx      context.Context
		Ref      string
		Blob     io.Reader
		Metadata registry.PushMetadata
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}

// ResolveRef calls ResolveRefFunc.
func (mock *RegistryMock) ResolveRef(ctx context.Context, ref string) (digest.Digest, error) {
	if mock.ResolveRefFunc == nil {
		panic("RegistryMock.ResolveRefFunc: method is nil but Registry.ResolveRef was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockResolveRef.Lock()
	mock.calls.ResolveRef = append(mock.calls.ResolveRef, callInfo)
	mock.lockResolveRef.Unlock()
	return mock.ResolveRefFunc(ctx, ref)
}

// ResolveRefCalls gets all the calls that were made to ResolveRef.
// Check the length with:
//
//	len(mockedRegistry.ResolveRefCalls())
func (mock *RegistryMock) ResolveRefCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockResolveRef.RLock()
	calls = mock.calls.ResolveRef
	mock.lockResolveRef.RUnlock()
	return calls
}
