// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/meigma/blobber/v2/internal/tar"
	"io"
	"sync"
)

// Ensure, that ExtractorMock does implement tar.Extractor.
// If this is not the case, regenerate this file with moq.
var _ tar.Extractor = &ExtractorMock{}

// ExtractorMock is a mock implementation of tar.Extractor.
//
//	func TestSomethingThatUsesExtractor(t *testing.T) {
//
//		// make and configure a mocked tar.Extractor
//		mockedExtractor := &ExtractorMock{
//			ExtractFunc: func(ctx context.Context, r io.Reader, destDir string, filter tar.EntryFilter) error {
//				panic("mock out the Extract method")
//			},
//		}
//
//		// use mockedExtractor in code that requires tar.Extractor
//		// and then make assertions.
//
//	}
type ExtractorMock struct {
	// ExtractFunc mocks the Extract method.
	ExtractFunc func(ctx context.Context, r io.Reader, destDir string, filter tar.EntryFilter) error

	// calls tracks calls to the methods.
	calls struct {
		// Extract holds details about calls to the Extract method.
		Extract []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R io.Reader
			// DestDir is the destDir argument value.
			DestDir string
			// Filter is the filter argument value.
			Filter tar.EntryFilter
		}
	}
	lockExtract sync.RWMutex
}

// Extract calls ExtractFunc.
func (mock *ExtractorMock) Extract(ctx context.Context, r io.Reader, destDir string, filter tar.EntryFilter) error {
	if mock.ExtractFunc == nil {
		panic("ExtractorMock.ExtractFunc: method is nil but Extractor.Extract was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		R       io.Reader
		DestDir string
		Filter  tar.EntryFilter
	}{
		Ctx:     ctx,
		R:       r,
		DestDir: destDir,
		Filter:  filter,
	}
	mock.lockExtract.Lock()
	mock.calls.Extract = append(mock.calls.Extract, callInfo)
	mock.lockExtract.Unlock()
	return mock.ExtractFunc(ctx, r, destDir, filter)
}

// ExtractCalls gets all the calls that were made to Extract.
// Check the length with:
//
//	len(mockedExtractor.ExtractCalls())
func (mock *ExtractorMock) ExtractCalls() []struct {
	Ctx     context.Context
	R       io.Reader
	DestDir string
	Filter  tar.EntryFilter
} {
	var calls []struct {
		Ctx     context.Context
		R       io.Reader
		DestDir string
		Filter  tar.EntryFilter
	}
	mock.lockExtract.RLock()
	calls = mock.calls.Extract
	mock.lockExtract.RUnlock()
	return calls
}
