// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/meigma/blobber/v2/internal/tar"
	"sync"
)

// Ensure, that PathValidatorMock does implement tar.PathValidator.
// If this is not the case, regenerate this file with moq.
var _ tar.PathValidator = &PathValidatorMock{}

// PathValidatorMock is a mock implementation of tar.PathValidator.
//
//	func TestSomethingThatUsesPathValidator(t *testing.T) {
//
//		// make and configure a mocked tar.PathValidator
//		mockedPathValidator := &PathValidatorMock{
//			ValidatePathFunc: func(path string) error {
//				panic("mock out the ValidatePath method")
//			},
//			ValidateSymlinkFunc: func(destDir string, linkPath string, target string) error {
//				panic("mock out the ValidateSymlink method")
//			},
//		}
//
//		// use mockedPathValidator in code that requires tar.PathValidator
//		// and then make assertions.
//
//	}
type PathValidatorMock struct {
	// ValidatePathFunc mocks the ValidatePath method.
	ValidatePathFunc func(path string) error

	// ValidateSymlinkFunc mocks the ValidateSymlink method.
	ValidateSymlinkFunc func(destDir string, linkPath string, target string) error

	// calls tracks calls to the methods.
	calls struct {
		// ValidatePath holds details about calls to the ValidatePath method.
		ValidatePath []struct {
			// Path is the path argument value.
			Path string
		}
		// ValidateSymlink holds details about calls to the ValidateSymlink method.
		ValidateSymlink []struct {
			// DestDir is the destDir argument value.
			DestDir string
			// LinkPath is the linkPath argument value.
			LinkPath string
			// Target is the target argument value.
			Target string
		}
	}
	lockValidatePath    sync.RWMutex
	lockValidateSymlink sync.RWMutex
}

// ValidatePath calls ValidatePathFunc.
func (mock *PathValidatorMock) ValidatePath(path string) error {
	if mock.ValidatePathFunc == nil {
		panic("PathValidatorMock.ValidatePathFunc: method is nil but PathValidator.ValidatePath was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockValidatePath.Lock()
	mock.calls.ValidatePath = append(mock.calls.ValidatePath, callInfo)
	mock.lockValidatePath.Unlock()
	return mock.ValidatePathFunc(path)
}

// ValidatePathCalls gets all the calls that were made to ValidatePath.
// Check the length with:
//
//	len(mockedPathValidator.ValidatePathCalls())
func (mock *PathValidatorMock) ValidatePathCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockValidatePath.RLock()
	calls = mock.calls.ValidatePath
	mock.lockValidatePath.RUnlock()
	return calls
}

// ValidateSymlink calls ValidateSymlinkFunc.
func (mock *PathValidatorMock) ValidateSymlink(destDir string, linkPath string, target string) error {
	if mock.ValidateSymlinkFunc == nil {
		panic("PathValidatorMock.ValidateSymlinkFunc: method is nil but PathValidator.ValidateSymlink was just called")
	}
	callInfo := struct {
		DestDir  string
		LinkPath string
		Target   string
	}{
		DestDir:  destDir,
		LinkPath: linkPath,
		Target:   target,
	}
	mock.lockValidateSymlink.Lock()
	mock.calls.ValidateSymlink = append(mock.calls.ValidateSymlink, callInfo)
	mock.lockValidateSymlink.Unlock()
	return mock.ValidateSymlinkFunc(destDir, linkPath, target)
}

// ValidateSymlinkCalls gets all the calls that were made to ValidateSymlink.
// Check the length with:
//
//	len(mockedPathValidator.ValidateSymlinkCalls())
func (mock *PathValidatorMock) ValidateSymlinkCalls() []struct {
	DestDir  string
	LinkPath string
	Target   string
} {
	var calls []struct {
		DestDir  string
		LinkPath string
		Target   string
	}
	mock.lockValidateSymlink.RLock()
	calls = mock.calls.ValidateSymlink
	mock.lockValidateSymlink.RUnlock()
	return calls
}
