// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/meigma/blobber/v2/internal/tar"
	"io"
	"io/fs"
	"sync"
)

// Ensure, that WriterMock does implement tar.Writer.
// If this is not the case, regenerate this file with moq.
var _ tar.Writer = &WriterMock{}

// WriterMock is a mock implementation of tar.Writer.
//
//	func TestSomethingThatUsesWriter(t *testing.T) {
//
//		// make and configure a mocked tar.Writer
//		mockedWriter := &WriterMock{
//			WriteToFunc: func(ctx context.Context, dst io.Writer, src fs.FS) error {
//				panic("mock out the WriteTo method")
//			},
//		}
//
//		// use mockedWriter in code that requires tar.Writer
//		// and then make assertions.
//
//	}
type WriterMock struct {
	// WriteToFunc mocks the WriteTo method.
	WriteToFunc func(ctx context.Context, dst io.Writer, src fs.FS) error

	// calls tracks calls to the methods.
	calls struct {
		// WriteTo holds details about calls to the WriteTo method.
		WriteTo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dst is the dst argument value.
			Dst io.Writer
			// Src is the src argument value.
			Src fs.FS
		}
	}
	lockWriteTo sync.RWMutex
}

// WriteTo calls WriteToFunc.
func (mock *WriterMock) WriteTo(ctx context.Context, dst io.Writer, src fs.FS) error {
	if mock.WriteToFunc == nil {
		panic("WriterMock.WriteToFunc: method is nil but Writer.WriteTo was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Dst io.Writer
		Src fs.FS
	}{
		Ctx: ctx,
		Dst: dst,
		Src: src,
	}
	mock.lockWriteTo.Lock()
	mock.calls.WriteTo = append(mock.calls.WriteTo, callInfo)
	mock.lockWriteTo.Unlock()
	return mock.WriteToFunc(ctx, dst, src)
}

// WriteToCalls gets all the calls that were made to WriteTo.
// Check the length with:
//
//	len(mockedWriter.WriteToCalls())
func (mock *WriterMock) WriteToCalls() []struct {
	Ctx context.Context
	Dst io.Writer
	Src fs.FS
} {
	var calls []struct {
		Ctx context.Context
		Dst io.Writer
		Src fs.FS
	}
	mock.lockWriteTo.RLock()
	calls = mock.calls.WriteTo
	mock.lockWriteTo.RUnlock()
	return calls
}
